package visitors;

public enum PlayerVisitorState 
{
	JUMPBALL, TEAMREBOUND, PLAYERREBOUND, TEAMTURNOVER, PLAYERTURNOVER, 
	TEAMVIOLATION, PLAYERVIOLATION, SHOT, TIMEOUT, SUB, PLAYERFOUL, TEAMFOUL, 
	DOUBLEFOUL, FREETHROW, PLAYERTECH, DOUBLETECH, TEAMTECH, EJECTION;
}
